# @generated
# @autocargo from //hphp/hack/src/parser:hh_autoimport_rust
# Signature
[package]
name = "hh_autoimport_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hh_autoimport.rs"]

[lib]
path = "../../hh_autoimport.rs"

[dependencies]
lazy_static = "1.4"
# @end of Signature
