# @generated
# @autocargo from //hphp/hack/src/parser:rewriter
# Signature<<667553245b2f8cbabffe112ec6f041a8a63f0039>>
[package]
name = "rewriter"
edition = "2018"
version = "0.0.0"
include = ["../../rewriter.rs"]

[lib]
path = "../../rewriter.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
# @end of Signature<<667553245b2f8cbabffe112ec6f041a8a63f0039>>
