# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_type_const
# Signature<<3ac4559b58fd4ef8d87c6eface0af1a30bf6d34c>>
[package]
name = "hhas_type_const"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_type_const.rs"]

[lib]
path = "../../hhas_type_const.rs"

[dependencies]
runtime = { path = "../runtime" }
# @end of Signature<<3ac4559b58fd4ef8d87c6eface0af1a30bf6d34c>>
