# @generated
# @autocargo from //hphp/hack/src/decl:decl_rust_ffi
# Signature<<49b696b2dee7443eaded2cf40907d0f92e19fa82>>
[package]
name = "decl_rust_ffi"
edition = "2018"
version = "0.0.0"
include = ["../rust_decl_ffi.rs"]

[lib]
path = "../rust_decl_ffi.rs"

[dependencies]
decl_rust = { path = "../decl_rust" }
ocamlrep_ocamlpool = { path = "../../ocamlrep_ocamlpool" }
oxidized = { path = "../../oxidized" }
# @end of Signature<<49b696b2dee7443eaded2cf40907d0f92e19fa82>>
