# @generated
# @autocargo from //hphp/hack/src/parser/api:decl_mode_parser
# Signature<<952640f1d2206844c26cced9d50e531f8cab5456>>
[package]
name = "decl_mode_parser"
edition = "2018"
version = "0.0.0"
include = ["../../decl_mode_parser.rs"]

[lib]
path = "../../decl_mode_parser.rs"

[dependencies]
decl_mode_smart_constructors = { path = "../../../cargo/decl_mode_parser" }
parser = { path = "../../../core" }
stack_limit = { path = "../../../../utils/stack_limit" }
# @end of Signature<<952640f1d2206844c26cced9d50e531f8cab5456>>
