# @generated
# @autocargo from //hphp/hack/src/oxidized:oxidized
# Signature<<f300015b302c6d3237f8d6d3cfef4007453faf56>>
[package]
name = "oxidized"
edition = "2018"
version = "0.0.0"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
ocamlrep = { path = "../ocamlrep" }
ocamlrep_derive = { path = "../ocamlrep_derive" }
ocaml = "0.8"
serde = { version = "1.0", features = ["derive", "rc"] }

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<f300015b302c6d3237f8d6d3cfef4007453faf56>>
