# @generated
# @autocargo from //hphp/hack/src/hhbc:unique_list_rust
# Signature<<4bd88c7d2c7c170cb28136a9fbe8fae5f4ea17ea>>
[package]
name = "unique_list_rust"
edition = "2018"
version = "0.0.0"
include = ["../../unique_list.rs"]

[lib]
path = "../../unique_list.rs"

[dependencies]
indexmap = "1.3"
# @end of Signature<<4bd88c7d2c7c170cb28136a9fbe8fae5f4ea17ea>>
