# @generated
# @autocargo from //hphp/hack/src/parser/coroutine:coroutine_lowerer
# Signature<<a59f757a073b658356f1cd4f3ada58a9ed39d335>>
[package]
name = "coroutine_lowerer"
edition = "2018"
version = "0.0.0"
include = ["../../coroutine_lowerer.rs"]

[lib]
path = "../../coroutine_lowerer.rs"

[dependencies]
ocamlrep = { path = "../../../../ocamlrep" }
parser_core_types = { path = "../../../cargo/core_types" }
rust_to_ocaml = { path = "../../../cargo/rust_to_ocaml" }
ocaml = "0.8"
# @end of Signature<<a59f757a073b658356f1cd4f3ada58a9ed39d335>>
