# @generated
# @autocargo from //hphp/hack/src/utils:stack_limit
# Signature<<a9e72a483c8bf507e4a72f3f5bceb5d06b0c756e>>
[package]
name = "stack_limit"
edition = "2018"
version = "0.0.0"
include = ["lib.rs", "retry.rs"]

[lib]
path = "lib.rs"
# @end of Signature<<a9e72a483c8bf507e4a72f3f5bceb5d06b0c756e>>
