# @generated
# @autocargo from //hphp/hack/src/utils:stack_limit
# Signature
[package]
name = "stack_limit"
edition = "2018"
version = "0.0.0"
include = ["lib.rs", "retry.rs"]

[lib]
path = "lib.rs"
# @end of Signature
