# @generated
# @autocargo from //hphp/hack/src/providers:decl_provider_rust
# Signature
[package]
name = "decl_provider_rust"
edition = "2018"
version = "0.0.0"
include = ["../../decl_provider.rs"]

[lib]
path = "../../decl_provider.rs"

[dependencies]
oxidized = { path = "../../../oxidized" }
# @end of Signature
