# @generated
# @autocargo from //hphp/hack/src/utils/perf:stats_rust
# Signature
[package]
name = "stats_rust"
edition = "2018"
version = "0.0.0"
include = ["../../perf_stats.rs"]

[lib]
path = "../../perf_stats.rs"
# @end of Signature
