# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_pos_rust
# Signature<<29a06836ca6461d4a77f82cd85000b04df9d07fb>>
[package]
name = "hhas_pos_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_pos.rs"]

[lib]
path = "../../hhas_pos.rs"

[dependencies]
oxidized = { path = "../../../oxidized" }
# @end of Signature<<29a06836ca6461d4a77f82cd85000b04df9d07fb>>
