# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_pu_rust
# Signature
[package]
name = "emit_pu_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_pu.rs"]

[lib]
path = "../../emit_pu.rs"

[dependencies]
oxidized = { path = "../../../oxidized" }
# @end of Signature
