# @generated
# @autocargo from //hphp/hack/src/hhbc:hhbc_id_rust
# Signature<<1efe3fa67530881b1edfb30801f13a0d66f4d4e9>>
[package]
name = "hhbc_id_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhbc_id.rs"]

[lib]
path = "../../hhbc_id.rs"

[dependencies]
hhbc_string_utils_rust = { path = "../string_utils" }
# @end of Signature<<1efe3fa67530881b1edfb30801f13a0d66f4d4e9>>
