# @generated
# @autocargo from //hphp/hack/src/parser/ppl:rust_ppl_class_rewriter
# Signature<<b583da5aea7c84a4b48d3d61028a7d69653db3b1>>
[package]
name = "rust_ppl_class_rewriter"
edition = "2018"
version = "0.0.0"
include = ["../../rust_ppl_class_rewriter.rs"]

[lib]
path = "../../rust_ppl_class_rewriter.rs"

[dependencies]
parser_core_types = { path = "../../../cargo/core_types" }
rewriter = { path = "../../../cargo/rewriter" }
rust_coroutine = { path = "../../../coroutine/cargo/rust_coroutine" }
rust_editable_positioned_syntax = { path = "../../../cargo/editable_positioned_syntax" }
lazy_static = "1.4"
# @end of Signature<<b583da5aea7c84a4b48d3d61028a7d69653db3b1>>
