# @generated
# @autocargo from //hphp/hack/src/parser:rust_parser_errors_ffi
# Signature<<44af429317180aa78df4dbc64d40667704df3ac8>>
[package]
name = "rust_parser_errors_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../../rust_parser_errors_ffi.rs"]

[lib]
path = "../../../rust_parser_errors_ffi.rs"
crate-type = ["lib", "staticlib"]

[dependencies]
ocamlrep = { path = "../../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../../ocamlrep_ocamlpool" }
oxidized = { path = "../../../../oxidized" }
parser_core_types = { path = "../../core_types" }
rust_parser_errors = { path = ".." }
rust_to_ocaml = { path = "../../rust_to_ocaml" }
ocaml = "0.8"
# @end of Signature<<44af429317180aa78df4dbc64d40667704df3ac8>>
