# @generated
# @autocargo from //hphp/hack/src/hhbc:hhbc_ast_rust
# Signature<<547b17e46a4f54291b3e79e9dbd31dbe3b3093ae>>
[package]
name = "hhbc_ast_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhbc_ast.rs"]

[lib]
path = "../../hhbc_ast.rs"

[dependencies]
env = { path = "../env" }
hhbc_id_rust = { path = "../hhbc_id" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
runtime = { path = "../runtime" }
bitflags = "1.2"
# @end of Signature<<547b17e46a4f54291b3e79e9dbd31dbe3b3093ae>>
