[workspace]
members = [
    "src/facts",
    "src/facts/ffi",
    "src/parser",
    "src/parser/core_types",
    "src/parser/errors",
    "src/parser/errors/ffi",
    "src/parser/ffi",
    "src/utils",
    "src/utils/ocamlpool_rust",
    "test",
]
