# @generated
# @autocargo from //hphp/hack/src/hhbc:label_rust
# Signature<<9f79f9f496b932713049712dc88073347b15be70>>
[package]
name = "label_rust"
edition = "2018"
version = "0.0.0"
include = ["../../label.rs"]

[lib]
path = "../../label.rs"
# @end of Signature<<9f79f9f496b932713049712dc88073347b15be70>>
