# @generated
# @autocargo from //hphp/hack/src/hhbc:label_rust
# Signature
[package]
name = "label_rust"
edition = "2018"
version = "0.0.0"
include = ["../../label.rs"]

[lib]
path = "../../label.rs"
# @end of Signature
