# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_symbol_refs_rust
# Signature
[package]
name = "hhas_symbol_refs_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_symbol_refs.rs"]

[lib]
path = "../../hhas_symbol_refs.rs"
# @end of Signature
