# @generated
# @autocargo from //hphp/hack/src/parser:smart_constructors
# Signature<<7e7252d2a8a7c8978fc815c6fde479a9062f2e1f>>
[package]
name = "smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../../smart_constructors.rs", "../../smart_constructors_generated.rs", "../../smart_constructors_wrappers.rs"]

[lib]
path = "../../smart_constructors.rs"

[dependencies]
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_derive = { path = "../../../ocamlrep_derive" }
parser_core_types = { path = "../core_types" }
# @end of Signature<<7e7252d2a8a7c8978fc815c6fde479a9062f2e1f>>
