# @generated
# @autocargo from //hphp/hack/src/parser:positioned_smart_constructors
# Signature<<ff6b68cf413ff48f175f36a8b3aeed2f30d33cd3>>
[package]
name = "positioned_smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../../positioned_smart_constructors.rs"]

[lib]
path = "../../positioned_smart_constructors.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
smart_constructors = { path = "../smart_constructors" }
syntax_smart_constructors = { path = "../syntax_smart_constructors" }
# @end of Signature<<ff6b68cf413ff48f175f36a8b3aeed2f30d33cd3>>
