# @generated
# @autocargo from //hphp/hack/src/hhbc:string_utils_bench
# Signature<<285d2526962fc997c7b54acce92631edfd4604a0>>
[package]
name = "string_utils_bench"
edition = "2018"
version = "0.0.0"
include = ["../../string_utils_bench.rs"]

[[bin]]
name = "string_utils_bench"
path = "../../string_utils_bench.rs"

[dependencies]
hhbc_string_utils_rust = { path = "../string_utils" }
# @end of Signature<<285d2526962fc997c7b54acce92631edfd4604a0>>
