# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_type
# Signature<<44f0514b0c81ad2ea66c16bc763a5588e5ef83bb>>
[package]
name = "hhas_type"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_type.rs"]

[lib]
path = "../../hhas_type.rs"

[dependencies]
emit_fatal_rust = { path = "../emit_fatal" }
bitflags = "1.2"
# @end of Signature<<44f0514b0c81ad2ea66c16bc763a5588e5ef83bb>>
