# @generated
# @autocargo from //hphp/hack/src/utils:ocaml_helper
# Signature<<df6b6baca3e8e2d17063145821515921ad134cbf>>
[package]
name = "ocaml_helper"
edition = "2018"
version = "0.0.0"
include = ["../ocaml_helper.rs"]

[lib]
path = "../ocaml_helper.rs"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<df6b6baca3e8e2d17063145821515921ad134cbf>>
