# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_param_rust
# Signature<<9a0fdc11e20633545080c5996b4ff56ab886ced1>>
[package]
name = "hhas_param_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_param.rs"]

[lib]
path = "../../hhas_param.rs"

[dependencies]
hhas_attribute_rust = { path = "../hhas_attribute" }
hhas_type = { path = "../hhas_type" }
label_rust = { path = "../label" }
oxidized = { path = "../../../oxidized" }
# @end of Signature<<9a0fdc11e20633545080c5996b4ff56ab886ced1>>
