# @generated
# @autocargo from //hphp/hack/src/parser/api:minimal_parser
# Signature<<1a18fb4aaab2d461cc156efa0e1662900bd476d4>>
[package]
name = "minimal_parser"
edition = "2018"
version = "0.0.0"
include = ["../../minimal_parser.rs"]

[lib]
path = "../../minimal_parser.rs"

[dependencies]
minimal_smart_constructors = { path = "../../../cargo/minimal_parser" }
parser = { path = "../../../core" }
stack_limit = { path = "../../../../utils/stack_limit" }
# @end of Signature<<1a18fb4aaab2d461cc156efa0e1662900bd476d4>>
