# @generated
# @autocargo from //hphp/hack/src/parser/api:direct_decl_parser
# Signature<<48c7263e53dc61ad3ee2a2c9802dfe6d2e37424a>>
[package]
name = "direct_decl_parser"
edition = "2018"
version = "0.0.0"
include = ["../../direct_decl_parser.rs"]

[lib]
path = "../../direct_decl_parser.rs"

[dependencies]
direct_decl_smart_constructors = { path = "../../../../decl/direct_decl_smart_constructors" }
parser = { path = "../../../core" }
parser_core_types = { path = "../../../cargo/core_types" }
stack_limit = { path = "../../../../utils/stack_limit" }
# @end of Signature<<48c7263e53dc61ad3ee2a2c9802dfe6d2e37424a>>
