# @generated
# @autocargo from //hphp/hack/src/name_index:hh_name_index
# Signature<<57c3f723ddfbed26feb852efca64e10040d50f9b>>
[package]
name = "hh_name_index"
edition = "2018"
version = "0.0.0"
include = ["main.rs"]

[[bin]]
name = "hh_name_index"
path = "main.rs"

[dependencies]
names = { path = "sqlite" }
oxidized = { path = "../oxidized" }
rusqlite = "0.21"
structopt = "0.3"
# @end of Signature<<57c3f723ddfbed26feb852efca64e10040d50f9b>>
