# @generated
# @autocargo from //hphp/hack/src/decl:decl_rust
# Signature<<1ef9984f437e1ccb94ae5a536ba8ea9b4ec07ca9>>
[package]
name = "decl_rust"
edition = "2018"
version = "0.0.0"
include = ["../direct_decl_parser.rs", "../lib.rs"]

[lib]
path = "../lib.rs"

[dependencies]
direct_decl_parser = { path = "../../parser/api/cargo/direct_decl_parser" }
direct_decl_smart_constructors = { path = "../direct_decl_smart_constructors" }
flatten_smart_constructors = { path = "../../parser/cargo/flatten_smart_constructors" }
hh_autoimport_rust = { path = "../../parser/cargo/hh_autoimport" }
hhbc_string_utils_rust = { path = "../../hhbc/cargo/string_utils" }
mode_parser = { path = "../../parser/cargo/mode_parser" }
naming_special_names_rust = { path = "../../naming" }
ocamlrep = { path = "../../ocamlrep" }
oxidized = { path = "../../oxidized" }
parser_core_types = { path = "../../parser/cargo/core_types" }
rust-crypto = "0.2"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<1ef9984f437e1ccb94ae5a536ba8ea9b4ec07ca9>>
