# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_constant_rust
# Signature
[package]
name = "hhas_constant_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_constant.rs"]

[lib]
path = "../../hhas_constant.rs"

[dependencies]
hhbc_id_rust = { path = "../hhbc_id" }
instruction_sequence_rust = { path = "../instruction_sequence" }
runtime = { path = "../runtime" }
# @end of Signature
