# @generated
# @autocargo from //hphp/hack/src/hhbc:env
# Signature<<5039fb34cfe6fc4966af4118f371bbe60f746036>>
[package]
name = "env"
edition = "2018"
version = "0.0.0"
include = ["../../emitter.rs", "../../env.rs", "../../iterator.rs", "../../jump_targets.rs"]

[lib]
path = "../../env.rs"

[dependencies]
ast_scope_rust = { path = "../ast_scope" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
rx_rust = { path = "../rx" }
bitflags = "1.2"
# @end of Signature<<5039fb34cfe6fc4966af4118f371bbe60f746036>>
