# @generated
# @autocargo from //hphp/hack/src/utils/perf:profile_rust
# Signature<<0549da1d0cd11c91763d536c21258ad256b2bfd2>>
[package]
name = "profile_rust"
edition = "2018"
version = "0.0.0"
include = ["../../profile.rs"]

[lib]
path = "../../profile.rs"

[dependencies]
libc = "0.2"
# @end of Signature<<0549da1d0cd11c91763d536c21258ad256b2bfd2>>
