# @generated
# @autocargo from //hphp/hack/src/utils:escaper
# Signature
[package]
name = "escaper"
edition = "2018"
version = "0.0.0"
include = ["../escaper.rs"]

[lib]
path = "../escaper.rs"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature
