# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_record_def_rust
# Signature<<ea1d1e8e500e7ba1f17fb6c749f728618869db6f>>
[package]
name = "hhas_record_def_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_record_def.rs"]

[lib]
path = "../../hhas_record_def.rs"

[dependencies]
hhas_type = { path = "../hhas_type" }
hhbc_id_rust = { path = "../hhbc_id" }
runtime = { path = "../runtime" }
# @end of Signature<<ea1d1e8e500e7ba1f17fb6c749f728618869db6f>>
