# @generated
# @autocargo from //hphp/hack/src/facts:facts_rust
# Signature
[package]
name = "facts_rust"
edition = "2018"
version = "0.0.0"
include = ["../../facts.rs", "../../facts_parser.rs", "../../lib.rs"]

[lib]
path = "../../lib.rs"

[dependencies]
escaper = { path = "../../../utils/escaper" }
facts_parser = { path = "../../../parser/api/cargo/facts_parser" }
facts_smart_constructors = { path = "../facts_smart_constructors" }
flatten_smart_constructors = { path = "../../../parser/cargo/flatten_smart_constructors" }
hhbc_string_utils_rust = { path = "../../../hhbc/cargo/string_utils" }
mode_parser = { path = "../../../parser/cargo/mode_parser" }
ocamlrep = { path = "../../../ocamlrep" }
oxidized = { path = "../../../oxidized" }
parser_core_types = { path = "../../../parser/cargo/core_types" }
rust-crypto = "0.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature
