# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_adata_rust
# Signature<<d89cae2780966aa5ab411512aa95ed60fa413f35>>
[package]
name = "emit_adata_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_adata.rs"]

[lib]
path = "../../emit_adata.rs"

[dependencies]
env = { path = "../env" }
options = { path = "../options" }
bitflags = "1.2"
# @end of Signature<<d89cae2780966aa5ab411512aa95ed60fa413f35>>
