# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_adata_rust
# Signature
[package]
name = "emit_adata_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_adata.rs"]

[lib]
path = "../../emit_adata.rs"

[dependencies]
env = { path = "../env" }
hhbc_ast_rust = { path = "../hhbc_ast" }
instruction_sequence_rust = { path = "../instruction_sequence" }
options = { path = "../options" }
runtime = { path = "../runtime" }
bitflags = "1.2"
# @end of Signature
