# @generated
# @autocargo from //hphp/hack/src/utils/ocamlpool_rust:ocamlpool_rust
# Signature<<0a3e3210cf3cc769c0af4d4ae5b8c5c0c9a6941b>>
[package]
name = "ocamlpool_rust"
edition = "2018"
version = "0.0.0"
include = ["lib.rs", "utils.rs"]

[lib]
path = "lib.rs"

[dependencies]
ocamlrep = { path = "../../ocamlrep" }
libc = "0.2"
ocaml = "0.8"
# @end of Signature<<0a3e3210cf3cc769c0af4d4ae5b8c5c0c9a6941b>>
