# @generated
# @autocargo from //hphp/hack/src/facts:rust_facts_ffi
# Signature<<fd1c1f8fd26f41f0cb2a150100e94f6d8e1e676d>>
[package]
name = "rust_facts_ffi"
edition = "2018"
version = "0.0.0"
include = ["../rust_facts_ffi.rs"]

[lib]
path = "../rust_facts_ffi.rs"
crate-type = ["lib", "staticlib"]

[dependencies]
facts_rust = { path = "../cargo/facts_rust" }
hhbc_string_utils_rust = { path = "../../hhbc/cargo/string_utils" }
ocamlrep = { path = "../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../ocamlrep_ocamlpool" }
oxidized = { path = "../../oxidized" }
ocaml = "0.8"
# @end of Signature<<fd1c1f8fd26f41f0cb2a150100e94f6d8e1e676d>>
