# @generated
# @autocargo from //hphp/hack/src/utils/html_entities:html_entities
# Signature
[package]
name = "html_entities"
edition = "2018"
version = "0.0.0"
include = ["decoder.rs", "html_entities.rs"]

[lib]
path = "html_entities.rs"

[dependencies]
ocaml_helper = { path = "../ocaml_helper" }
lazy_static = "1.4"
regex = "1.3"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature
