# @generated
# @autocargo from //hphp/hack/src/parser:flatten_smart_constructors
# Signature<<3bd1b3f26b91027064b1064b0ee7cf9b9035661c>>
[package]
name = "flatten_smart_constructors"
edition = "2018"
version = "0.0.0"
include = ["../../flatten_smart_constructors.rs"]

[lib]
path = "../../flatten_smart_constructors.rs"

[dependencies]
parser_core_types = { path = "../core_types" }
smart_constructors = { path = "../smart_constructors" }
# @end of Signature<<3bd1b3f26b91027064b1064b0ee7cf9b9035661c>>
