# @generated
# @autocargo from //hphp/hack/src/hhbc:hhas_attribute_rust
# Signature<<863fad6ec6ab4b48940a542fb4c7dc101b64f580>>
[package]
name = "hhas_attribute_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhas_attribute.rs"]

[lib]
path = "../../hhas_attribute.rs"

[dependencies]
naming_special_names_rust = { path = "../../../naming" }
runtime = { path = "../runtime" }
# @end of Signature<<863fad6ec6ab4b48940a542fb4c7dc101b64f580>>
