# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_memoize_helpers_rust
# Signature<<76ca96065cd86aba58f4089a0ac940c4cf08ecc0>>
[package]
name = "emit_memoize_helpers_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_memoize_helpers.rs"]

[lib]
path = "../../emit_memoize_helpers.rs"

[dependencies]
emit_fatal_rust = { path = "../emit_fatal" }
hhas_param_rust = { path = "../hhas_param" }
hhbc_ast_rust = { path = "../hhbc_ast" }
instruction_sequence_rust = { path = "../instruction_sequence" }
local_rust = { path = "../local" }
oxidized = { path = "../../../oxidized" }
# @end of Signature<<76ca96065cd86aba58f4089a0ac940c4cf08ecc0>>
