# @generated
# @autocargo from //hphp/hack/src/ocamlrep:ocamlrep
# Signature<<2c07c3069536dc33e5e708f934636337fb1066c4>>
[package]
name = "ocamlrep"
edition = "2018"
version = "0.0.0"
include = ["*.rs"]

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }

[dev-dependencies]
ocamlrep_derive = { path = "../ocamlrep_derive" }
ocamlrep_ocamlpool = { path = "../ocamlrep_ocamlpool" }
ocaml = "0.8"
# @end of Signature<<2c07c3069536dc33e5e708f934636337fb1066c4>>
