# @generated
# @autocargo from //hphp/hack/src/utils:line_break_map
# Signature<<9698b3013c759a512c19df0ec85915830811c78c>>
[package]
name = "line_break_map"
edition = "2018"
version = "0.0.0"
include = ["../line_break_map.rs"]

[lib]
path = "../line_break_map.rs"

[dev-dependencies]
pretty_assertions = "0.6"
# @end of Signature<<9698b3013c759a512c19df0ec85915830811c78c>>
