# @generated
# @autocargo from //hphp/hack/src/hhbc:options_ffi
# Signature<<c5e6050ecbe9610a77fdac3141e3a2ba6a5c129a>>
[package]
name = "options_ffi"
edition = "2018"
version = "0.0.0"
include = ["../../options_ffi.rs"]

[lib]
path = "../../options_ffi.rs"

[dependencies]
hhbc_string_utils_rust = { path = "../string_utils" }
ocamlrep = { path = "../../../ocamlrep" }
ocamlrep_ocamlpool = { path = "../../../ocamlrep_ocamlpool" }
options = { path = "../options" }
ocaml = "0.8"
# @end of Signature<<c5e6050ecbe9610a77fdac3141e3a2ba6a5c129a>>
