# @generated
# @autocargo from //hphp/hack/src/hhbc:emit_function_rust
# Signature<<30b2833468c396f47b1c80bb367561c32eb7163a>>
[package]
name = "emit_function_rust"
edition = "2018"
version = "0.0.0"
include = ["../../emit_function.rs", "../../emit_memoize_function.rs"]

[lib]
path = "../../emit_function.rs"

[dependencies]
ast_scope_rust = { path = "../ast_scope" }
closure_convert_rust = { path = "../closure_convert" }
emit_attribute_rust = { path = "../emit_attribute" }
emit_body_rust = { path = "../emit_body" }
emit_fatal_rust = { path = "../emit_fatal" }
emit_memoize_helpers_rust = { path = "../emit_memoize_helpers" }
env = { path = "../env" }
hhas_attribute_rust = { path = "../hhas_attribute" }
hhas_body_rust = { path = "../hhas_body" }
hhas_function_rust = { path = "../hhas_function" }
hhas_pos_rust = { path = "../hhas_pos" }
hhbc_id_rust = { path = "../hhbc_id" }
instruction_sequence_rust = { path = "../instruction_sequence" }
label_rust = { path = "../label" }
local_rust = { path = "../local" }
naming_special_names_rust = { path = "../../../naming" }
options = { path = "../options" }
oxidized = { path = "../../../oxidized" }
runtime = { path = "../runtime" }
rx_rust = { path = "../rx" }
# @end of Signature<<30b2833468c396f47b1c80bb367561c32eb7163a>>
