# @generated
# @autocargo from //hphp/hack/src/hhbc:hhbc_hhas_rust
# Signature<<4a8bacd4d58f24766f56f52846a190cf0305cd4f>>
[package]
name = "hhbc_hhas_rust"
edition = "2018"
version = "0.0.0"
include = ["../../hhbc_hhas.rs"]

[lib]
path = "../../hhbc_hhas.rs"

[dependencies]
hhas_program_rust = { path = "../hhas_program" }
oxidized = { path = "../../../oxidized" }
# @end of Signature<<4a8bacd4d58f24766f56f52846a190cf0305cd4f>>
