# @generated
# @autocargo from //hphp/hack/src/hhbc:hhbc_hhas_rust
# Signature
[package]
name = "hhbc_hhas_rust"
edition = "2018"
version = "0.0.0"
include = ["../../print.rs", "../../print_env.rs", "../../write.rs"]

[lib]
path = "../../print.rs"

[dependencies]
hhas_program_rust = { path = "../hhas_program" }
hhas_record_def_rust = { path = "../hhas_record_def" }
hhbc_id_rust = { path = "../hhbc_id" }
oxidized = { path = "../../../oxidized" }
thiserror = "1.0"
# @end of Signature
