# @generated
# @autocargo from //hphp/hack/src/parser/api:verify_parser
# Signature<<75abed27b8251ea41a10c60a61688581f5eb6b29>>
[package]
name = "verify_parser"
edition = "2018"
version = "0.0.0"
include = ["../../verify_parser.rs"]

[lib]
path = "../../verify_parser.rs"

[dependencies]
parser = { path = "../../../core" }
stack_limit = { path = "../../../../utils/stack_limit" }
verify_smart_constructors = { path = "../../../cargo/verify_parser" }
# @end of Signature<<75abed27b8251ea41a10c60a61688581f5eb6b29>>
