# @generated
# @autocargo from //hphp/hack/src/parser/api:coroutine_parser_leak_tree
# Signature<<4a71ac13936059af00674056cd46184bc057499a>>
[package]
name = "coroutine_parser_leak_tree"
edition = "2018"
version = "0.0.0"
include = ["../../coroutine_parser_leak_tree.rs"]

[lib]
path = "../../coroutine_parser_leak_tree.rs"

[dependencies]
coroutine_smart_constructors = { path = "../../../cargo/coroutine_smart_constructors" }
parser = { path = "../../../core" }
stack_limit = { path = "../../../../utils/stack_limit" }
# @end of Signature<<4a71ac13936059af00674056cd46184bc057499a>>
