# @generated
# @autocargo from //hphp/hack/src/hh_codegen:hh_codegen
# Signature
[package]
name = "hh_codegen"
edition = "2018"
version = "0.0.0"
include = ["**/*.rs"]

[[bin]]
name = "hh_codegen"
path = "hh_codegen.rs"

[dependencies]
clap = "2.33"
itertools = "0.8"
proc-macro2 = "1.0"
quote = "1.0"
rust-crypto = "0.2"
syn = { version = "1.0", features = ["full", "visit", "visit-mut", "fold", "extra-traits"] }
synstructure = "0.12"
# @end of Signature
